server:
  port: 9000
  
spring:
  application:
    name: stock-service
    
  data:
    mongodb:
      #host: ${MONGO_HOST:localhost}
      host: 192.168.99.100
      port: 27017
      database: stock-market
      
  jpa:
    show-sql: true
  cloud:
    discovery:
      enabled: false
    
#  kafka:
#    consumer:#      bootstrap-servers: 192.168.99.100:9092
#      group-id: group-1
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:#      bootstrap-servers: 192.168.99.100:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    
eureka:
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      defaultZone: http://192.168.99.100:8761/eureka
  instance:
    prefer-ip-address: true
    
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG  
    
management:
  endpoints:
    web:
      exposure:
        include: '*'