server:
  port: 9000
  
spring:
  application:
    name: stock-service
    
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: stock-market
      
  jpa:
    show-sql: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG  
    
management:
  endpoints:
    web:
      exposure:
        include: '*'