server:
  port: 9000
  
spring:
  application:
    name: stock-service
    
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stock-market
      
  jpa:
    show-sql: true
    
eureka:
  client:
    enabled: true
    eureka-server-u-r-l-context: http://localhost:8761
    
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG